image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-card-delivery.jar &
  - chmod +x gradlew

build_script:
  #  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации, построенном с использованием Selenium
  - ./gradlew test --info -Dselenide.headless=true   #для включения headless режима в проекте, построенном с использованием Selenide, будет выглядеть так